### ISSUE TITLE
Load ELF file's section data into OS from SD card

### ISSUE THREAD

**Issue by Bryce-Dixon** [BtheDestroyer/PICOnsole#6]
Depends on #5.

Useful reference: https://youtu.be/nC1U1LJQL8o

**Comment by Bryce-Dixon** [comment]
Commit 9cf5e0d6d35185ba328e5420e899751311ba4eef adds header reading. Still need to read actual sections to find `.piconsole_program_init` and `.piconsole_program_update` (as well as all the other sections for loading into flash memory)

**Comment by BtheDestroyer** [comment]
Seems to be functional. Next step would be figuring out the sectors that need to be erased rather than erasing the whole flash partition to speed up the loading process.
